name: Weather Pipeline

on:
  schedule:
    - cron: '38 17 * * *'   # jam 00:38 WIB
    - cron: '38 5 * * *'    # jam 12:38 WIB
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests gspread google-auth

      - name: Jalankan pipeline
        env:
          WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python run_once.py